// <auto-generated />
using System;
using AbilityHub.Usage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AbilityHub.Usage.Migrations
{
    [DbContext(typeof(UsageDbContext))]
    [Migration("20260621143619_AddActivityInProgress")]
    partial class AddActivityInProgress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AbilityHub.Usage.Entities.ActivityRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("CompletedViaAction")
                        .HasColumnType("bit");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int?>("ErrorsCount")
                        .HasColumnType("int");

                    b.Property<int?>("HintsShown")
                        .HasColumnType("int");

                    b.Property<bool>("InProgress")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.Property<bool?>("StartedViaAction")
                        .HasColumnType("bit");

                    b.Property<int?>("StepsCompleted")
                        .HasColumnType("int");

                    b.Property<int?>("StepsTotal")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChildId", "ApplicationId", "OccurredAt");

                    b.ToTable("ActivityRecords");
                });

            modelBuilder.Entity("AbilityHub.Usage.Entities.UsageSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChildId", "ApplicationId", "StartedAt");

                    b.ToTable("UsageSessions");
                });

            modelBuilder.Entity("AbilityHub.Usage.Entities.WeeklyCheckIn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayContextNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HelpLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoodAfter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoodBefore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformanceQuality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SafetyIncident")
                        .HasColumnType("bit");

                    b.Property<string>("SafetyIncidentNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("UsesSkillOutsideApp")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ChildId", "WeekStartDate")
                        .IsUnique();

                    b.ToTable("WeeklyCheckIns");
                });
#pragma warning restore 612, 618
        }
    }
}
